import {
  KeyRound,
  Key,
  KeySquare,
  LockKeyhole,
  LockKeyholeOpen,
  DoorOpen,
  DoorClosed,
  Smartphone,
  SmartphoneCharging,
  MonitorSmartphone,
  ScanFace,
  ScanEye,
  Vault,
  ShieldPlus,
  Power,
  PowerOff,
  PlugZap,
  Plug,
  BadgeCheck,
  PackageOpen,
  PackageSearch,
  RotateCw,
  RefreshCw,
  Watch,
  ShieldAlert,
  ShieldCheck,
  Shield,
  Copy,
  Radio,
  Fingerprint,
  Cpu,
  Siren,
  Wrench,
  Car,
  CarFront,
  Lock,
  LockOpen,
  Unlock,
  Settings,
  Settings2,
  Cog,
  Zap,
  Clock,
  Timer,
  PhoneCall,
  Phone,
  MapPin,
  Truck,
  Hammer,
  Drill,
  Scissors,
  Package,
  PackageCheck,
  Star,
  CheckCircle2,
  AlertTriangle,
  Battery,
  BatteryCharging,
  Bluetooth,
  Wifi,
  Radar,
  Scan,
  ScanLine,
  QrCode,
  CreditCard,
  DollarSign,
  Users,
  User,
  UserCheck,
  Building,
  Building2,
  Home,
  Warehouse,
  Store,
  ShoppingBag,
  ShoppingCart,
  Cctv,
  Video,
  Camera,
  Bell,
  BellRing,
  HelpCircle,
  LifeBuoy,
  Headphones,
  MessageCircle,
  Mail,
  Send,
  Navigation,
  Compass,
  Route,
  Map,
  Gauge,
  Activity,
  TrendingUp,
  Award,
  Medal,
  ThumbsUp,
  Handshake,
  ClipboardCheck,
  ClipboardList,
  FileCheck,
  FileText,
  Layers,
  Boxes,
  Box,
  Puzzle,
  Sparkles,
  Flame,
  Droplet,
  Sun,
  Moon,
  Cloud,
  CarTaxiFront,
  Bike,
  Bus,
  TowerControl,
  CircuitBoard,
  Usb,
  MousePointer2,
  Terminal,
  Barcode,
  type LucideIcon,
} from "lucide-react";

export const SERVICE_ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: "KeyRound", icon: KeyRound },
  { name: "Key", icon: Key },
  { name: "KeySquare", icon: KeySquare },
  { name: "Lock", icon: Lock },
  { name: "LockOpen", icon: LockOpen },
  { name: "LockKeyhole", icon: LockKeyhole },
  { name: "LockKeyholeOpen", icon: LockKeyholeOpen },
  { name: "Unlock", icon: Unlock },
  { name: "DoorOpen", icon: DoorOpen },
  { name: "DoorClosed", icon: DoorClosed },
  { name: "Smartphone", icon: Smartphone },
  { name: "SmartphoneCharging", icon: SmartphoneCharging },
  { name: "MonitorSmartphone", icon: MonitorSmartphone },
  { name: "ScanFace", icon: ScanFace },
  { name: "ScanEye", icon: ScanEye },
  { name: "Vault", icon: Vault },
  { name: "ShieldPlus", icon: ShieldPlus },
  { name: "Power", icon: Power },
  { name: "PowerOff", icon: PowerOff },
  { name: "PlugZap", icon: PlugZap },
  { name: "Plug", icon: Plug },
  { name: "BadgeCheck", icon: BadgeCheck },
  { name: "PackageOpen", icon: PackageOpen },
  { name: "PackageSearch", icon: PackageSearch },
  { name: "RotateCw", icon: RotateCw },
  { name: "RefreshCw", icon: RefreshCw },
  { name: "Watch", icon: Watch },
  { name: "ShieldAlert", icon: ShieldAlert },
  { name: "ShieldCheck", icon: ShieldCheck },
  { name: "Shield", icon: Shield },
  { name: "Copy", icon: Copy },
  { name: "Radio", icon: Radio },
  { name: "Fingerprint", icon: Fingerprint },
  { name: "Cpu", icon: Cpu },
  { name: "Siren", icon: Siren },
  { name: "Wrench", icon: Wrench },
  { name: "Car", icon: Car },
  { name: "CarFront", icon: CarFront },
  { name: "Settings", icon: Settings },
  { name: "Settings2", icon: Settings2 },
  { name: "Cog", icon: Cog },
  { name: "Zap", icon: Zap },
  { name: "Clock", icon: Clock },
  { name: "Timer", icon: Timer },
  { name: "PhoneCall", icon: PhoneCall },
  { name: "Phone", icon: Phone },
  { name: "MapPin", icon: MapPin },
  { name: "Truck", icon: Truck },
  { name: "Hammer", icon: Hammer },
  { name: "Drill", icon: Drill },
  { name: "Scissors", icon: Scissors },
  { name: "Package", icon: Package },
  { name: "PackageCheck", icon: PackageCheck },
  { name: "Star", icon: Star },
  { name: "CheckCircle2", icon: CheckCircle2 },
  { name: "AlertTriangle", icon: AlertTriangle },
  { name: "Battery", icon: Battery },
  { name: "BatteryCharging", icon: BatteryCharging },
  { name: "Bluetooth", icon: Bluetooth },
  { name: "Wifi", icon: Wifi },
  { name: "Radar", icon: Radar },
  { name: "Scan", icon: Scan },
  { name: "ScanLine", icon: ScanLine },
  { name: "QrCode", icon: QrCode },
  { name: "CreditCard", icon: CreditCard },
  { name: "DollarSign", icon: DollarSign },
  { name: "Users", icon: Users },
  { name: "User", icon: User },
  { name: "UserCheck", icon: UserCheck },
  { name: "Building", icon: Building },
  { name: "Building2", icon: Building2 },
  { name: "Home", icon: Home },
  { name: "Warehouse", icon: Warehouse },
  { name: "Store", icon: Store },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Cctv", icon: Cctv },
  { name: "Video", icon: Video },
  { name: "Camera", icon: Camera },
  { name: "Bell", icon: Bell },
  { name: "BellRing", icon: BellRing },
  { name: "HelpCircle", icon: HelpCircle },
  { name: "LifeBuoy", icon: LifeBuoy },
  { name: "Headphones", icon: Headphones },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "Mail", icon: Mail },
  { name: "Send", icon: Send },
  { name: "Navigation", icon: Navigation },
  { name: "Compass", icon: Compass },
  { name: "Route", icon: Route },
  { name: "Map", icon: Map },
  { name: "Gauge", icon: Gauge },
  { name: "Activity", icon: Activity },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "Award", icon: Award },
  { name: "Medal", icon: Medal },
  { name: "ThumbsUp", icon: ThumbsUp },
  { name: "Handshake", icon: Handshake },
  { name: "ClipboardCheck", icon: ClipboardCheck },
  { name: "ClipboardList", icon: ClipboardList },
  { name: "FileCheck", icon: FileCheck },
  { name: "FileText", icon: FileText },
  { name: "Layers", icon: Layers },
  { name: "Boxes", icon: Boxes },
  { name: "Box", icon: Box },
  { name: "Puzzle", icon: Puzzle },
  { name: "Sparkles", icon: Sparkles },
  { name: "Flame", icon: Flame },
  { name: "Droplet", icon: Droplet },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "Cloud", icon: Cloud },
  { name: "CarTaxiFront", icon: CarTaxiFront },
  { name: "Bike", icon: Bike },
  { name: "Bus", icon: Bus },
  { name: "TowerControl", icon: TowerControl },
  { name: "CircuitBoard", icon: CircuitBoard },
  { name: "Usb", icon: Usb },
  { name: "MousePointer2", icon: MousePointer2 },
  { name: "Terminal", icon: Terminal },
  { name: "Barcode", icon: Barcode },
];

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  SERVICE_ICON_OPTIONS.map((o) => [o.name, o.icon])
);

export function getIconByName(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return ICON_MAP[name] ?? null;
}
